/*
 * This file is generated by jOOQ.
*/
package tech.codingclub.helix.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;

import tech.codingclub.helix.tables.Follower;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FollowerRecord extends TableRecordImpl<FollowerRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = -1359872276;

    /**
     * Setter for <code>twitter.follower.user_id</code>.
     */
    public void setUserId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>twitter.follower.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>twitter.follower.following_id</code>.
     */
    public void setFollowingId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>twitter.follower.following_id</code>.
     */
    public Long getFollowingId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Follower.FOLLOWER.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Follower.FOLLOWER.FOLLOWING_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getFollowingId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getFollowingId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FollowerRecord value1(Long value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FollowerRecord value2(Long value) {
        setFollowingId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FollowerRecord values(Long value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FollowerRecord
     */
    public FollowerRecord() {
        super(Follower.FOLLOWER);
    }

    /**
     * Create a detached, initialised FollowerRecord
     */
    public FollowerRecord(Long userId, Long followingId) {
        super(Follower.FOLLOWER);

        set(0, userId);
        set(1, followingId);
    }
}
