/*
 * This file is generated by jOOQ.
*/
package tech.codingclub.helix.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.TableRecordImpl;

import tech.codingclub.helix.tables.Music;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MusicRecord extends TableRecordImpl<MusicRecord> implements Record10<String, String, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = -440942275;

    /**
     * Setter for <code>twitter.music.parent_link</code>.
     */
    public void setParentLink(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>twitter.music.parent_link</code>.
     */
    public String getParentLink() {
        return (String) get(0);
    }

    /**
     * Setter for <code>twitter.music.child_link</code>.
     */
    public void setChildLink(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>twitter.music.child_link</code>.
     */
    public String getChildLink() {
        return (String) get(1);
    }

    /**
     * Setter for <code>twitter.music.album</code>.
     */
    public void setAlbum(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>twitter.music.album</code>.
     */
    public String getAlbum() {
        return (String) get(2);
    }

    /**
     * Setter for <code>twitter.music.duration</code>.
     */
    public void setDuration(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>twitter.music.duration</code>.
     */
    public String getDuration() {
        return (String) get(3);
    }

    /**
     * Setter for <code>twitter.music.lyricist</code>.
     */
    public void setLyricist(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>twitter.music.lyricist</code>.
     */
    public String getLyricist() {
        return (String) get(4);
    }

    /**
     * Setter for <code>twitter.music.singers</code>.
     */
    public void setSingers(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>twitter.music.singers</code>.
     */
    public String getSingers() {
        return (String) get(5);
    }

    /**
     * Setter for <code>twitter.music.music_director</code>.
     */
    public void setMusicDirector(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>twitter.music.music_director</code>.
     */
    public String getMusicDirector() {
        return (String) get(6);
    }

    /**
     * Setter for <code>twitter.music.download_128</code>.
     */
    public void setDownload_128(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>twitter.music.download_128</code>.
     */
    public String getDownload_128() {
        return (String) get(7);
    }

    /**
     * Setter for <code>twitter.music.download_256</code>.
     */
    public void setDownload_256(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>twitter.music.download_256</code>.
     */
    public String getDownload_256() {
        return (String) get(8);
    }

    /**
     * Setter for <code>twitter.music.image_url</code>.
     */
    public void setImageUrl(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>twitter.music.image_url</code>.
     */
    public String getImageUrl() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, String, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Music.MUSIC.PARENT_LINK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Music.MUSIC.CHILD_LINK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Music.MUSIC.ALBUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Music.MUSIC.DURATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Music.MUSIC.LYRICIST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Music.MUSIC.SINGERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Music.MUSIC.MUSIC_DIRECTOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Music.MUSIC.DOWNLOAD_128;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Music.MUSIC.DOWNLOAD_256;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Music.MUSIC.IMAGE_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getParentLink();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getChildLink();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getAlbum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getDuration();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getLyricist();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getSingers();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getMusicDirector();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getDownload_128();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getDownload_256();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getImageUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getParentLink();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getChildLink();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getAlbum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDuration();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getLyricist();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getSingers();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getMusicDirector();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getDownload_128();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getDownload_256();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getImageUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MusicRecord value1(String value) {
        setParentLink(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MusicRecord value2(String value) {
        setChildLink(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MusicRecord value3(String value) {
        setAlbum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MusicRecord value4(String value) {
        setDuration(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MusicRecord value5(String value) {
        setLyricist(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MusicRecord value6(String value) {
        setSingers(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MusicRecord value7(String value) {
        setMusicDirector(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MusicRecord value8(String value) {
        setDownload_128(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MusicRecord value9(String value) {
        setDownload_256(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MusicRecord value10(String value) {
        setImageUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MusicRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MusicRecord
     */
    public MusicRecord() {
        super(Music.MUSIC);
    }

    /**
     * Create a detached, initialised MusicRecord
     */
    public MusicRecord(String parentLink, String childLink, String album, String duration, String lyricist, String singers, String musicDirector, String download_128, String download_256, String imageUrl) {
        super(Music.MUSIC);

        set(0, parentLink);
        set(1, childLink);
        set(2, album);
        set(3, duration);
        set(4, lyricist);
        set(5, singers);
        set(6, musicDirector);
        set(7, download_128);
        set(8, download_256);
        set(9, imageUrl);
    }
}
